ddns:
  host: xiongdw.tpddns.cn
server:
  port: 2021
spring:
  application:
    name: feign-provider
  cloud:
    consul:
      host: ${ddns.host}
      port: 8500
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${server.port}
        healthCheckInterval: 15s
        heartbeat:
          enabled: true