ddns:
  host: xiongdw.tpddns.cn
server:
  port: 2022
spring:
  application:
    name: feign-consumer
  cloud:
    consul:
      host: ${ddns.host}
      port: 8500
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${server.port}
        healthCheckInterval: 15s
        heartbeat:
          enabled: true