server:
  port: 2022
spring:
  application:
    name: feign-consumer
  cloud:
    consul:
      host: 192.168.20.128
      port: 8500
      discovery:
        enabled: true
        instanceId: ${spring.application.name}
        healthCheckInterval: 15s
        heartbeat:
          enabled: true